using DataFrames

# replace this line with tree (and the next one with the predictable) generated by id3.jl file

function getPrediction(tree, row)
  
  # test if is the final node
  if get(tree, "final", false) != false
    return get(tree, "final", false)
  end
  
  nodeKey = cleanType("String", string(keys(tree)))
  
  atributeValue = cleanType("UTF8String", string(row[Symbol(nodeKey)]))
  
  # test if the value of node atribute is the same in the next node
  for node in tree[nodeKey]
    subtree = Dict(node[2])
    if node[1] == atributeValue
      return getPrediction(subtree, row)
    end
  end
  
  return "Can't predict the value"
end

function cleanType(stringType, text)
  text = replace(text, stringType , "")
  text = replace(text, "[\"" , "")
  text = replace(text, "\"]" , "")
  return text
end

function guessFunction(tree, inputFile)
  final = []
  for row in eachrow(inputFile)
    push!(final, row)
    push!(final, getPrediction(tree, row))
    push!(final, " --- ")
  end
  
  return final
end

if length(ARGS) == 2
  inputFile = readtable(ARGS[1])
  outputFilename = string(ARGS[2])

  
  outputFile = guessFunction(tree, inputFile)
  writedlm(outputFilename, outputFile)
  
else
  println("incorrect arguments, try run:")
  println("julia id3Test.jl data/beachTest.csv output.txt")
  println("for more info see the readme file, yes the file's name is README and I can't imagine why.")
end
